# -*- coding: utf-8 -*-
"""1_perceptron.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1erSqDVK31xjzD-BO2ScZTEzAVedHiaYR
"""

from sklearn.datasets import load_digits
digits=load_digits(n_class=5)
digits.data

digits.target

len(digits.data)

digits.data[0]

img=digits.data[0].reshape((8,8))

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
plt.imshow(img)

from sklearn.model_selection import train_test_split

train_X,test_X,train_y,test_y=train_test_split(digits.data,digits.target,test_size=0.1,random_state=423)

len(test_X)

from sklearn.linear_model import Perceptron
model=Perceptron()

model.fit(train_X,train_y)

import joblib

joblib.dump(model,"trained.joblib",compress=True)

model = joblib.load('trained.joblib')

results=model.predict(test_X)

print(results)

print(test_y)

import numpy as np

tmp=results-test_y

np.count_nonzero(tmp)

(len(test_y)-np.count_nonzero(tmp))/len(test_y)

from sklearn.metrics import accuracy_score

accuracy_score(results,test_y)

plt.imshow(test_X[0].reshape((8,8)))

print(test_y[0])
print(results[0])

np.where((test_y-results)!=0)

np.savetxt('result.csv',results,delimiter=',',fmt='%d')

from sklearn.datasets import load_iris
iris=load_iris()

model2 = Perceptron()

train2_X,test2_X,train2_y,test2_y=train_test_split(iris.data,iris.target,test_size=0.2,random_state=423)

model2.fit(train2_X,train2_y)

results2=model2.predict(test2_X)

print(results2)

print(test2_y)

accuracy_score(test2_y,results2)

np.savetxt('result.csv',results2,delimiter=',',fmt='%d')

"""# 新しいセクション"""